### ISSUE TITLE
Missing property to cancel remaining when deliver order

### ISSUE THREAD

**Issue by Tasteful** [sveawebpay/svea-sdk-dotnet#104]
In the https://paymentadminapi.svea.com/documentation/#/?id=deliver-order it is described that the `CancelRemaining` can be set when the order is marked as delivered but that property is missing in the SDK. Is there some other method that should be used to achieve the same behavior?

https://github.com/sveawebpay/svea-sdk-dotnet/blob/4950d52e23a53acf1c1af070a3bfb122c5f64410/src/Svea.WebPay.SDK/PaymentAdminApi/Request/DeliveryRequest.cs

**Comment by lounge** [comment]
@Tasteful Fixed in v3.1.0
