### ISSUE TITLE
HttpResponseException have internal accessibility

### ISSUE THREAD

**Issue by Tasteful** [sveawebpay/svea-sdk-dotnet#13]
The `HttpResponseException` have accessibility `internal`, this make it hard to catch the exception because we need to catch on `Exceptoion` and then use reflection to get the correct result back.

Can the `HttpResponseException` be changed to `public` accessibility?

https://github.com/sveawebpay/svea-sdk-dotnet/blob/ff22ee3ad9b86aafd26d918755f55f2aebb35c37/src/Svea.WebPay.SDK/Exceptions/HttpResponseException.cs#L6

**Comment by lounge** [comment]
@Tasteful Fixed in release 2.1.1
