### ISSUE TITLE
ZeroSum

### ISSUE THREAD

**Issue by Tasteful** [sveawebpay/svea-sdk-dotnet#172]
If I don't navigate wrong I think the commits for the ZeroSum is missing in the latest release, can you dobbel check?

https://github.com/sveawebpay/svea-sdk-dotnet/blob/v4.1.0/src/Svea.WebPay.SDK/PaymentAdminApi/PaymentType.cs

**Comment by lounge** [comment]
We have published a new version 4.1.1 with this fixed
