### ISSUE TITLE
JsonException for expired orders

### ISSUE THREAD

**Issue by Flybring** [sveawebpay/svea-sdk-dotnet#273]
I am currently using `await client.PaymentAdmin.GetOrder(checkoutOrderId);` to retrieve order information, but occasionally I encounter a JsonException error. The JSON response contains the following data: `"OrderStatus": "Expired"`
However, the "Expired" value does not appear in the OrderStatus enum, I guess this might be causing the issue.

The error message I receive is:
`JsonException: The JSON value could not be converted to Svea.WebPay.SDK.PaymentAdminApi.Response.OrderResponseObject. Path: $.OrderStatus | LineNumber: 0 | BytePositionInLine: 81.`

Additionally, it would be great if the ExpirationDate mentioned in the documentation could be added as well 😄

**Comment by Flybring** [comment]
@lounge Is there any estimate for the next release? It would be nice to be able to handle these cases without ugly workarounds :)

**Comment by lounge** [comment]
@Flybring Sorry I will check with the team

**Comment by dusanbobicic** [comment]
Published in 4.2.1 right now.
