### ISSUE TITLE
Include original exception as inner exception

### ISSUE THREAD

**Issue by Tasteful** [sveawebpay/svea-sdk-dotnet#69]
In the integration code that using the Svea SDK we are getting error logs that not contains to full stacktrace and have found this exception that not will include the original exception as inner exception for the new exception that is created. Should be good if that can be included as well.

https://github.com/sveawebpay/svea-sdk-dotnet/blob/9d34b60fc55f647be9977600b9b2f58c93e68483/src/Svea.WebPay.SDK/SveaHttpClient.cs#L167

// Patric @ Litium

**Comment by lounge** [comment]
Could you please do a PR and link this issue. Thanks
