### ISSUE TITLE
Mobile pay

### ISSUE THREAD

**Issue by Tasteful** [sveawebpay/svea-sdk-dotnet#70]
We have a customer that trying to use MOBILEPAY in DK and the SDK throws exception. I can see that the missed types in the enums was added like 6 hours ago. Do we have any plan on release date for this?

// Patric @ Litium

**Comment by lounge** [comment]
It's beeing tested right now and will be released soon

**Comment by lounge** [comment]
@Tasteful This is now released in v2.4.0
